import { useEffect, useState, useRef, useCallback } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { ArrowLeft, Edit2, Save, X, Download, Copy, Search, Clock, Globe } from 'lucide-react';
import { formatDistanceToNow } from 'date-fns';
import { useTranscriptStore, useUIStore } from '../store';
import { fetchTranscript, updateTranscript } from '../lib/api';
import { jsPDF } from 'jspdf';

function formatTime(secs) {
  if (!secs) return '0:00';
  const m = Math.floor(secs / 60);
  const s = Math.floor(secs % 60);
  return `${m}:${s.toString().padStart(2, '0')}`;
}

function highlightText(text, query) {
  if (!query.trim()) return text;
  const regex = new RegExp(`(${query.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')})`, 'gi');
  const parts = text.split(regex);
  return parts.map((part, i) =>
    regex.test(part) ? <mark key={i} className="highlight">{part}</mark> : part
  );
}

export default function TranscriptViewer() {
  const { id } = useParams();
  const navigate = useNavigate();
  const { currentTranscript, setCurrentTranscript, isLoadingOne, setLoadingOne } = useTranscriptStore();
  const { addToast } = useUIStore();

  const [isEditing, setIsEditing] = useState(false);
  const [editTitle, setEditTitle] = useState('');
  const [editContent, setEditContent] = useState('');
  const [isSaving, setIsSaving] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const [activeSegIdx, setActiveSegIdx] = useState(null);

  useEffect(() => {
    async function load() {
      setLoadingOne(true);
      try {
        const data = await fetchTranscript(id);
        setCurrentTranscript(data);
        setEditTitle(data.title);
        setEditContent(data.content);
      } catch (err) {
        addToast({ type: 'error', message: err.message });
        navigate('/');
      } finally {
        setLoadingOne(false);
      }
    }
    load();
    return () => setCurrentTranscript(null);
  }, [id]);

  // Keyboard shortcuts
  useEffect(() => {
    function onKey(e) {
      if ((e.metaKey || e.ctrlKey) && e.key === 'e') {
        e.preventDefault();
        setIsEditing(true);
      }
      if ((e.metaKey || e.ctrlKey) && e.key === 's') {
        e.preventDefault();
        if (isEditing) handleSave();
      }
      if (e.key === 'Escape' && isEditing) {
        setIsEditing(false);
        setEditTitle(currentTranscript?.title || '');
        setEditContent(currentTranscript?.content || '');
      }
    }
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [isEditing, editTitle, editContent, currentTranscript]);

  async function handleSave() {
    setIsSaving(true);
    try {
      const updated = await updateTranscript(id, { title: editTitle, content: editContent });
      setCurrentTranscript(updated);
      setIsEditing(false);
      addToast({ type: 'success', message: 'Transcript saved' });
    } catch (err) {
      addToast({ type: 'error', message: err.message });
    } finally {
      setIsSaving(false);
    }
  }

  function copyToClipboard() {
    navigator.clipboard.writeText(currentTranscript?.content || '');
    addToast({ type: 'success', message: 'Copied to clipboard' });
  }

  function downloadTxt() {
    const blob = new Blob([currentTranscript?.content || ''], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${currentTranscript?.title || 'transcript'}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  function downloadPdf() {
    const doc = new jsPDF();
    const title = currentTranscript?.title || 'Transcript';
    const content = currentTranscript?.content || '';
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.text(title, 20, 20);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    doc.setTextColor(80, 80, 80);
    doc.text(`Generated by VoxAI • ${new Date().toLocaleDateString()}`, 20, 30);
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(11);
    const lines = doc.splitTextToSize(content, 170);
    doc.text(lines, 20, 45);
    doc.save(`${title}.pdf`);
  }

  if (isLoadingOne) {
    return (
      <div className="empty-state" style={{ height: '80vh' }}>
        <div className="spinner spinner-lg" />
      </div>
    );
  }

  if (!currentTranscript) return null;

  const segments = Array.isArray(currentTranscript.segments) ? currentTranscript.segments : [];

  return (
    <div className="animate-in">
      {/* Header */}
      <div className="page-header" style={{ flexWrap: 'wrap', gap: 12 }}>
        <div className="flex items-center gap-3" style={{ flex: 1, minWidth: 0 }}>
          <button className="btn btn-icon btn-ghost" onClick={() => navigate('/')}>
            <ArrowLeft size={18} />
          </button>
          <div style={{ flex: 1, minWidth: 0 }}>
            {isEditing ? (
              <input
                className="input-field"
                value={editTitle}
                onChange={(e) => setEditTitle(e.target.value)}
                style={{ fontSize: '1.25rem', fontWeight: 600, background: 'transparent', padding: '4px 8px' }}
                autoFocus
              />
            ) : (
              <h2 className="truncate">{currentTranscript.title}</h2>
            )}
            <div className="flex items-center gap-3" style={{ marginTop: 4, fontSize: '0.75rem', color: 'var(--text-muted)' }}>
              {currentTranscript.duration > 0 && (
                <span className="flex items-center gap-1"><Clock size={11} /> {formatTime(currentTranscript.duration)}</span>
              )}
              {currentTranscript.language && (
                <span className="flex items-center gap-1"><Globe size={11} /> {currentTranscript.language.toUpperCase()}</span>
              )}
              <span>{formatDistanceToNow(new Date(currentTranscript.createdAt), { addSuffix: true })}</span>
            </div>
          </div>
        </div>

        <div className="flex gap-2" style={{ flexShrink: 0 }}>
          {isEditing ? (
            <>
              <button className="btn btn-secondary btn-sm" onClick={() => { setIsEditing(false); setEditTitle(currentTranscript.title); setEditContent(currentTranscript.content); }}>
                <X size={14} /> Cancel <span className="kbd">Esc</span>
              </button>
              <button className="btn btn-primary btn-sm" onClick={handleSave} disabled={isSaving}>
                {isSaving ? <div className="spinner" /> : <Save size={14} />} Save <span className="kbd">⌘S</span>
              </button>
            </>
          ) : (
            <>
              <button className="btn btn-ghost btn-sm" onClick={copyToClipboard}><Copy size={14} /> Copy</button>
              <button className="btn btn-secondary btn-sm" onClick={downloadTxt}><Download size={14} /> TXT</button>
              <button className="btn btn-secondary btn-sm" onClick={downloadPdf}><Download size={14} /> PDF</button>
              <button className="btn btn-primary btn-sm" onClick={() => setIsEditing(true)}>
                <Edit2 size={14} /> Edit <span className="kbd">⌘E</span>
              </button>
            </>
          )}
        </div>
      </div>

      <div className="page-content">
        {/* Search bar */}
        {!isEditing && (
          <div className="input-field-icon" style={{ maxWidth: 380, marginBottom: 24 }}>
            <Search size={14} />
            <input
              className="input-field"
              placeholder="Search within transcript…"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
            />
          </div>
        )}

        {/* Content */}
        {isEditing ? (
          <textarea
            className="input-field"
            style={{ minHeight: 500, resize: 'vertical', lineHeight: 1.8, fontSize: '0.9375rem' }}
            value={editContent}
            onChange={(e) => setEditContent(e.target.value)}
          />
        ) : segments.length > 0 ? (
          <div className="card" style={{ padding: 8 }}>
            {segments.map((seg, i) => (
              <div
                key={seg.id ?? i}
                className={`transcript-segment${activeSegIdx === i ? ' active' : ''}`}
                onClick={() => setActiveSegIdx(i === activeSegIdx ? null : i)}
              >
                <span className="segment-time">{formatTime(seg.start)}</span>
                <span className="segment-text">
                  {highlightText(seg.text, searchQuery)}
                </span>
              </div>
            ))}
          </div>
        ) : (
          <div className="card" style={{ padding: 32 }}>
            <p style={{ lineHeight: 1.9, fontSize: '0.9375rem', color: 'var(--text)', whiteSpace: 'pre-wrap' }}>
              {highlightText(currentTranscript.content || '', searchQuery)}
            </p>
          </div>
        )}

        {/* Keyboard hints */}
        {!isEditing && (
          <div style={{ marginTop: 16, display: 'flex', gap: 16, fontSize: '0.75rem', color: 'var(--text-muted)' }}>
            <span><span className="kbd">⌘E</span> Edit</span>
            <span><span className="kbd">⌘S</span> Save</span>
            <span>Click segment to highlight</span>
          </div>
        )}
      </div>
    </div>
  );
}
